version: '3.7'
services:
  wh2o-db:
    container_name: wh2o-db
    image: mdillon/postgis:9.6
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: wh2o
      POSTGRES_PASSWORD: wh2o
      POSTGRES_DB: wh2o
    networks:
      - default
  wh2o-redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - default
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - "REDIS_HOST=localhost"
      - "REDIS_PORT=6379"
    ports:
    - "8081:8081"
    networks:
        - default
#  wh2o-api:
#    container_name: wh2o-api
#    image: drewalth/wh2o-api
#    build:
#      context: .
#      dockerfile: ./wh2o-api/Dockerfile
##    volumes:
##      - ./wh2o-api:/var/www
##      - ./wh2o-api/node_modules:/var/www/node_modules
#    ports:
#      - "3000:3000"
#    depends_on:
#      - wh2o-db
#    networks:
#      - default
networks:
  default:
    driver: bridge
